### ISSUE TITLE
Combine multiple Android fs libraries

### ISSUE THREAD

**Issue by derdilla** [derdilla/blood-pressure-monitor-fl#203]
- [X] https://pub.dev/packages/file_saver
~~- [ ] https://pub.dev/packages/file_picker~~
- [ ] https://pub.dev/packages/jsaver
- [ ] custom native file saving code

**Comment by NobodyForNothing** [comment]
You are right, it's best to support all platforms. Since this issue was created file_picker had 2 (3?) major versions, which look very promising. I removed it from the issue and added the platform specific code.

jsaver on the other hand is still not ideal and doesn't support linux/windows platforms anyways. I still depend on it because it's the only package I'm aware of that supports saving files to a directory the user picked once (`OPEN_DOCUMENT_TREE`). I opened a related feature request with file_picker and noticed some related PRs so this might be combined soon.

In general is solid support for more platforms currently quite difficult since there is still some manual testing involved with upgrades and data migrations. I agree tho that specifically Linux is quite important (for the reasons you mentioned and potentially linux phones). There is  a similar case for IOS with lots of people that could benefit from the app but no way for me to properly test the app and unfamiliar (expensive?) publishing.

**Comment by NobodyForNothing** [comment]
While debugging android build failures in the latest flutter beta jsaver blocks updating gradle (with that agp and flutter) from updating. Since jsaver seems to be unmaintained I'm considering a custom fork. @pimlie I saw you have a PR there, what do you think?

**Comment by NobodyForNothing** [comment]
Unfortunately `file_picker`s saveFile doesn't allow persisting directory access (they have a open PR like this). `file_saver` is a different use case. I asked around the flutter community and they couldn't help, so I think I will try my luck on a simple custom package.
