### ISSUE TITLE
Use different bluetooth library that supports all major platforms

### ISSUE THREAD

**Issue by pimlie** [derdilla/blood-pressure-monitor-fl#423]
### What you want:

Use a bluetooth library that supports all major platforms, not just Android/iOS.

Possible alternatives:
- https://pub.dev/packages/universal_ble
- https://pub.dev/packages/bluetooth_low_energy

I can help implement this if you'd like, but like your approval first :) 

Also for this and the other issues, maybe we can create a github project with tickets you'd like help with? Or at least add a label 'help-wanted' to those tickets and finalize the feature description. Not sure how much time you have and/or want to spend on this app but I can help with some tickets if they have a clear ask and you agree with them :)

### Why you want it:

The maintainer of https://github.com/chipweinberger/flutter_blue_plus has rejected PR's to add Linux & Web support to FBP, in the issue about adding Linux Support he says support will happen via wrappers but that implementation has big disadvantages.

**Comment by NobodyForNothing** [comment]
I choose flutter_blue_plus since it was the biggest ble library. your libraries look smaller which could mean less tested. Since they are all basically wrappers I think the size is fine. I would prefer bluetooth_low_energy since it has more doc coverage, but your call.

It would be great if you implemented this as I don't have a ble device (and this would have a low priority for me). This is an open source project, so anyone can pick any feature/issue they like to work on and submit a PR. Sorry if that wasn't clear from the README.
